# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'run2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(425, 456)
        MainWindow.setToolTip("")
        MainWindow.setStatusTip("")
        MainWindow.setWhatsThis("")
        MainWindow.setAccessibleName("")
        MainWindow.setAccessibleDescription("")
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setToolTip("")
        self.tabWidget.setStatusTip("")
        self.tabWidget.setWhatsThis("")
        self.tabWidget.setAccessibleName("")
        self.tabWidget.setAccessibleDescription("")
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setObjectName("tabWidget")
        self.Tests = QtWidgets.QWidget()
        self.Tests.setMinimumSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Tests.setFont(font)
        self.Tests.setObjectName("Tests")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Tests)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Dimensionality = QtWidgets.QGroupBox(self.Tests)
        self.Dimensionality.setToolTip("")
        self.Dimensionality.setStatusTip("")
        self.Dimensionality.setWhatsThis("")
        self.Dimensionality.setAccessibleName("")
        self.Dimensionality.setAccessibleDescription("")
        self.Dimensionality.setObjectName("Dimensionality")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Dimensionality)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.params_Dim = QtWidgets.QFrame(self.Dimensionality)
        self.params_Dim.setToolTip("")
        self.params_Dim.setStatusTip("")
        self.params_Dim.setWhatsThis("")
        self.params_Dim.setAccessibleName("")
        self.params_Dim.setAccessibleDescription("")
        self.params_Dim.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.params_Dim.setFrameShadow(QtWidgets.QFrame.Raised)
        self.params_Dim.setObjectName("params_Dim")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.params_Dim)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.params_Dim)
        self.label_2.setToolTip("")
        self.label_2.setStatusTip("")
        self.label_2.setWhatsThis("")
        self.label_2.setAccessibleName("")
        self.label_2.setAccessibleDescription("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.scaler_Dim = QtWidgets.QComboBox(self.params_Dim)
        self.scaler_Dim.setToolTip("")
        self.scaler_Dim.setStatusTip("")
        self.scaler_Dim.setWhatsThis("")
        self.scaler_Dim.setAccessibleName("")
        self.scaler_Dim.setAccessibleDescription("")
        self.scaler_Dim.setObjectName("scaler_Dim")
        self.scaler_Dim.addItem("")
        self.scaler_Dim.addItem("")
        self.scaler_Dim.addItem("")
        self.scaler_Dim.addItem("")
        self.scaler_Dim.addItem("")
        self.scaler_Dim.addItem("")
        self.scaler_Dim.addItem("")
        self.verticalLayout.addWidget(self.scaler_Dim)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.params_Dim)
        self.label.setToolTip("")
        self.label.setStatusTip("")
        self.label.setWhatsThis("")
        self.label.setAccessibleName("")
        self.label.setAccessibleDescription("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.PCA_Dim = QtWidgets.QDoubleSpinBox(self.params_Dim)
        self.PCA_Dim.setToolTip("Percentage, 0-1")
        self.PCA_Dim.setStatusTip("")
        self.PCA_Dim.setWhatsThis("")
        self.PCA_Dim.setAccessibleName("")
        self.PCA_Dim.setAccessibleDescription("")
        self.PCA_Dim.setMaximum(1.0)
        self.PCA_Dim.setSingleStep(0.05)
        self.PCA_Dim.setObjectName("PCA_Dim")
        self.verticalLayout.addWidget(self.PCA_Dim)
        self.horizontalLayout.addWidget(self.params_Dim)
        self.buttons_Dim = QtWidgets.QFrame(self.Dimensionality)
        self.buttons_Dim.setToolTip("")
        self.buttons_Dim.setStatusTip("")
        self.buttons_Dim.setWhatsThis("")
        self.buttons_Dim.setAccessibleName("")
        self.buttons_Dim.setAccessibleDescription("")
        self.buttons_Dim.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons_Dim.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons_Dim.setObjectName("buttons_Dim")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.buttons_Dim)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_LDA = QtWidgets.QPushButton(self.buttons_Dim)
        self.btn_LDA.setToolTip("")
        self.btn_LDA.setStatusTip("")
        self.btn_LDA.setWhatsThis("")
        self.btn_LDA.setAccessibleName("")
        self.btn_LDA.setAccessibleDescription("")
        self.btn_LDA.setObjectName("btn_LDA")
        self.verticalLayout_3.addWidget(self.btn_LDA)
        self.btn_PCA = QtWidgets.QPushButton(self.buttons_Dim)
        self.btn_PCA.setToolTip("")
        self.btn_PCA.setStatusTip("")
        self.btn_PCA.setWhatsThis("")
        self.btn_PCA.setAccessibleName("")
        self.btn_PCA.setAccessibleDescription("")
        self.btn_PCA.setObjectName("btn_PCA")
        self.verticalLayout_3.addWidget(self.btn_PCA)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem1)
        self.btn_PCA_Plot = QtWidgets.QPushButton(self.buttons_Dim)
        self.btn_PCA_Plot.setToolTip("")
        self.btn_PCA_Plot.setStatusTip("")
        self.btn_PCA_Plot.setWhatsThis("")
        self.btn_PCA_Plot.setAccessibleName("")
        self.btn_PCA_Plot.setAccessibleDescription("")
        self.btn_PCA_Plot.setObjectName("btn_PCA_Plot")
        self.verticalLayout_3.addWidget(self.btn_PCA_Plot)
        self.btn_PlotLDA = QtWidgets.QPushButton(self.buttons_Dim)
        self.btn_PlotLDA.setToolTip("")
        self.btn_PlotLDA.setStatusTip("")
        self.btn_PlotLDA.setWhatsThis("")
        self.btn_PlotLDA.setAccessibleName("")
        self.btn_PlotLDA.setAccessibleDescription("")
        self.btn_PlotLDA.setObjectName("btn_PlotLDA")
        self.verticalLayout_3.addWidget(self.btn_PlotLDA)
        self.horizontalLayout.addWidget(self.buttons_Dim)
        self.verticalLayout_2.addWidget(self.Dimensionality)
        self.testModels = QtWidgets.QGroupBox(self.Tests)
        self.testModels.setToolTip("")
        self.testModels.setStatusTip("")
        self.testModels.setWhatsThis("")
        self.testModels.setAccessibleName("")
        self.testModels.setAccessibleDescription("")
        self.testModels.setObjectName("testModels")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.testModels)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.params_Test = QtWidgets.QFrame(self.testModels)
        self.params_Test.setToolTip("")
        self.params_Test.setStatusTip("")
        self.params_Test.setWhatsThis("")
        self.params_Test.setAccessibleName("")
        self.params_Test.setAccessibleDescription("")
        self.params_Test.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.params_Test.setFrameShadow(QtWidgets.QFrame.Raised)
        self.params_Test.setObjectName("params_Test")
        self.gridLayout = QtWidgets.QGridLayout(self.params_Test)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_5 = QtWidgets.QFrame(self.params_Test)
        self.frame_5.setToolTip("")
        self.frame_5.setStatusTip("")
        self.frame_5.setWhatsThis("")
        self.frame_5.setAccessibleName("")
        self.frame_5.setAccessibleDescription("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.select_LDA = QtWidgets.QRadioButton(self.frame_5)
        self.select_LDA.setToolTip("")
        self.select_LDA.setStatusTip("")
        self.select_LDA.setWhatsThis("")
        self.select_LDA.setAccessibleName("")
        self.select_LDA.setAccessibleDescription("")
        self.select_LDA.setObjectName("select_LDA")
        self.horizontalLayout_3.addWidget(self.select_LDA)
        self.select_PCA = QtWidgets.QRadioButton(self.frame_5)
        self.select_PCA.setToolTip("Takes a long time to run")
        self.select_PCA.setStatusTip("")
        self.select_PCA.setWhatsThis("")
        self.select_PCA.setAccessibleName("")
        self.select_PCA.setAccessibleDescription("")
        self.select_PCA.setObjectName("select_PCA")
        self.horizontalLayout_3.addWidget(self.select_PCA)
        self.select_PCA.raise_()
        self.select_LDA.raise_()
        self.gridLayout.addWidget(self.frame_5, 3, 0, 1, 1)
        self.PCA_Test = QtWidgets.QDoubleSpinBox(self.params_Test)
        self.PCA_Test.setToolTip("Percentage, 0-1")
        self.PCA_Test.setStatusTip("")
        self.PCA_Test.setWhatsThis("")
        self.PCA_Test.setAccessibleName("")
        self.PCA_Test.setAccessibleDescription("")
        self.PCA_Test.setMaximum(1.0)
        self.PCA_Test.setSingleStep(0.05)
        self.PCA_Test.setObjectName("PCA_Test")
        self.gridLayout.addWidget(self.PCA_Test, 9, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.params_Test)
        self.label_5.setToolTip("")
        self.label_5.setStatusTip("")
        self.label_5.setWhatsThis("")
        self.label_5.setAccessibleName("")
        self.label_5.setAccessibleDescription("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.params_Test)
        self.label_3.setToolTip("")
        self.label_3.setStatusTip("")
        self.label_3.setWhatsThis("")
        self.label_3.setAccessibleName("")
        self.label_3.setAccessibleDescription("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.params_Test)
        self.buttons_Test = QtWidgets.QFrame(self.testModels)
        self.buttons_Test.setToolTip("")
        self.buttons_Test.setStatusTip("")
        self.buttons_Test.setWhatsThis("")
        self.buttons_Test.setAccessibleName("")
        self.buttons_Test.setAccessibleDescription("")
        self.buttons_Test.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons_Test.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons_Test.setObjectName("buttons_Test")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.buttons_Test)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.buttons_Test)
        self.label_4.setToolTip("")
        self.label_4.setStatusTip("")
        self.label_4.setWhatsThis("")
        self.label_4.setAccessibleName("")
        self.label_4.setAccessibleDescription("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.scaler_Test = QtWidgets.QComboBox(self.buttons_Test)
        self.scaler_Test.setToolTip("")
        self.scaler_Test.setStatusTip("")
        self.scaler_Test.setWhatsThis("")
        self.scaler_Test.setAccessibleName("")
        self.scaler_Test.setAccessibleDescription("")
        self.scaler_Test.setObjectName("scaler_Test")
        self.scaler_Test.addItem("")
        self.scaler_Test.addItem("")
        self.scaler_Test.addItem("")
        self.scaler_Test.addItem("")
        self.scaler_Test.addItem("")
        self.scaler_Test.addItem("")
        self.scaler_Test.addItem("")
        self.verticalLayout_4.addWidget(self.scaler_Test)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.btn_CompareModels = QtWidgets.QPushButton(self.buttons_Test)
        self.btn_CompareModels.setToolTip("Results saved to file")
        self.btn_CompareModels.setStatusTip("")
        self.btn_CompareModels.setWhatsThis("")
        self.btn_CompareModels.setAccessibleName("")
        self.btn_CompareModels.setAccessibleDescription("")
        self.btn_CompareModels.setIconSize(QtCore.QSize(16, 30))
        self.btn_CompareModels.setObjectName("btn_CompareModels")
        self.verticalLayout_4.addWidget(self.btn_CompareModels)
        self.horizontalLayout_2.addWidget(self.buttons_Test)
        self.buttons_Test.raise_()
        self.params_Test.raise_()
        self.verticalLayout_2.addWidget(self.testModels)
        self.tabWidget.addTab(self.Tests, "")
        self.Results = QtWidgets.QWidget()
        self.Results.setObjectName("Results")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.Results)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.parameters = QtWidgets.QGroupBox(self.Results)
        self.parameters.setToolTip("")
        self.parameters.setStatusTip("")
        self.parameters.setWhatsThis("")
        self.parameters.setAccessibleName("")
        self.parameters.setAccessibleDescription("")
        self.parameters.setObjectName("parameters")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.parameters)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.parameters)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setToolTip("")
        self.label_6.setStatusTip("")
        self.label_6.setWhatsThis("")
        self.label_6.setAccessibleName("")
        self.label_6.setAccessibleDescription("")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.box_Model = QtWidgets.QComboBox(self.frame_2)
        self.box_Model.setToolTip("")
        self.box_Model.setStatusTip("")
        self.box_Model.setWhatsThis("")
        self.box_Model.setAccessibleName("")
        self.box_Model.setAccessibleDescription("")
        self.box_Model.setObjectName("box_Model")
        self.box_Model.addItem("")
        self.box_Model.addItem("")
        self.box_Model.addItem("")
        self.box_Model.addItem("")
        self.box_Model.addItem("")
        self.box_Model.addItem("")
        self.box_Model.addItem("")
        self.horizontalLayout_5.addWidget(self.box_Model)
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setToolTip("")
        self.label_8.setStatusTip("")
        self.label_8.setWhatsThis("")
        self.label_8.setAccessibleName("")
        self.label_8.setAccessibleDescription("")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.box_Scaler = QtWidgets.QComboBox(self.frame_2)
        self.box_Scaler.setToolTip("")
        self.box_Scaler.setStatusTip("")
        self.box_Scaler.setWhatsThis("")
        self.box_Scaler.setAccessibleName("")
        self.box_Scaler.setAccessibleDescription("")
        self.box_Scaler.setObjectName("box_Scaler")
        self.box_Scaler.addItem("")
        self.box_Scaler.addItem("")
        self.box_Scaler.addItem("")
        self.box_Scaler.addItem("")
        self.box_Scaler.addItem("")
        self.box_Scaler.addItem("")
        self.box_Scaler.addItem("")
        self.horizontalLayout_5.addWidget(self.box_Scaler)
        self.verticalLayout_5.addWidget(self.frame_2)
        self.features = QtWidgets.QGroupBox(self.parameters)
        self.features.setToolTip("")
        self.features.setStatusTip("")
        self.features.setWhatsThis("")
        self.features.setAccessibleName("")
        self.features.setAccessibleDescription("")
        self.features.setObjectName("features")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.features)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_3 = QtWidgets.QFrame(self.features)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setToolTip("")
        self.label_10.setStatusTip("")
        self.label_10.setWhatsThis("")
        self.label_10.setAccessibleName("")
        self.label_10.setAccessibleDescription("")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.box_Feature = QtWidgets.QComboBox(self.frame_3)
        self.box_Feature.setToolTip("")
        self.box_Feature.setStatusTip("")
        self.box_Feature.setWhatsThis("")
        self.box_Feature.setAccessibleName("")
        self.box_Feature.setAccessibleDescription("")
        self.box_Feature.setObjectName("box_Feature")
        self.box_Feature.addItem("")
        self.box_Feature.addItem("")
        self.box_Feature.addItem("")
        self.box_Feature.addItem("")
        self.box_Feature.addItem("")
        self.box_Feature.addItem("")
        self.box_Feature.addItem("")
        self.box_Feature.addItem("")
        self.box_Feature.addItem("")
        self.box_Feature.addItem("")
        self.box_Feature.addItem("")
        self.box_Feature.addItem("")
        self.horizontalLayout_6.addWidget(self.box_Feature)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_7.addWidget(self.frame_3)
        self.frame = QtWidgets.QFrame(self.features)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.btn_combineFeatures = QtWidgets.QRadioButton(self.frame)
        self.btn_combineFeatures.setObjectName("btn_combineFeatures")
        self.horizontalLayout_4.addWidget(self.btn_combineFeatures)
        self.verticalLayout_7.addWidget(self.frame)
        self.label_11 = QtWidgets.QLabel(self.features)
        self.label_11.setToolTip("")
        self.label_11.setStatusTip("")
        self.label_11.setWhatsThis("")
        self.label_11.setAccessibleName("")
        self.label_11.setAccessibleDescription("")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_7.addWidget(self.label_11)
        self.listFeatures = QtWidgets.QListWidget(self.features)
        self.listFeatures.setToolTip("")
        self.listFeatures.setStatusTip("")
        self.listFeatures.setWhatsThis("")
        self.listFeatures.setAccessibleName("")
        self.listFeatures.setAccessibleDescription("")
        self.listFeatures.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listFeatures.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.listFeatures.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listFeatures.setLineWidth(3)
        self.listFeatures.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listFeatures.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listFeatures.setMovement(QtWidgets.QListView.Free)
        self.listFeatures.setFlow(QtWidgets.QListView.TopToBottom)
        self.listFeatures.setProperty("isWrapping", True)
        self.listFeatures.setResizeMode(QtWidgets.QListView.Adjust)
        self.listFeatures.setLayoutMode(QtWidgets.QListView.Batched)
        self.listFeatures.setGridSize(QtCore.QSize(100, 20))
        self.listFeatures.setViewMode(QtWidgets.QListView.ListMode)
        self.listFeatures.setModelColumn(0)
        self.listFeatures.setUniformItemSizes(False)
        self.listFeatures.setBatchSize(100)
        self.listFeatures.setWordWrap(False)
        self.listFeatures.setObjectName("listFeatures")
        item = QtWidgets.QListWidgetItem()
        self.listFeatures.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listFeatures.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listFeatures.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listFeatures.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listFeatures.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listFeatures.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listFeatures.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listFeatures.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listFeatures.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listFeatures.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listFeatures.addItem(item)
        self.verticalLayout_7.addWidget(self.listFeatures)
        self.label_11.raise_()
        self.frame.raise_()
        self.listFeatures.raise_()
        self.frame_3.raise_()
        self.verticalLayout_5.addWidget(self.features)
        self.verticalLayout_8.addWidget(self.parameters)
        self.frame_4 = QtWidgets.QFrame(self.Results)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_Results = QtWidgets.QPushButton(self.frame_4)
        self.btn_Results.setToolTip("Plots")
        self.btn_Results.setStatusTip("")
        self.btn_Results.setWhatsThis("")
        self.btn_Results.setAccessibleName("")
        self.btn_Results.setAccessibleDescription("")
        self.btn_Results.setObjectName("btn_Results")
        self.horizontalLayout_7.addWidget(self.btn_Results)
        self.btn_SaveModel = QtWidgets.QPushButton(self.frame_4)
        self.btn_SaveModel.setObjectName("btn_SaveModel")
        self.horizontalLayout_7.addWidget(self.btn_SaveModel)
        self.verticalLayout_8.addWidget(self.frame_4)
        self.tabWidget.addTab(self.Results, "")
        self.Classify = QtWidgets.QWidget()
        self.Classify.setObjectName("Classify")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.Classify)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.Classify)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_10.addWidget(self.label_9)
        self.frame_6 = QtWidgets.QFrame(self.Classify)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.text_file = QtWidgets.QLineEdit(self.frame_6)
        self.text_file.setToolTip("")
        self.text_file.setStatusTip("")
        self.text_file.setWhatsThis("")
        self.text_file.setAccessibleName("")
        self.text_file.setAccessibleDescription("")
        self.text_file.setObjectName("text_file")
        self.horizontalLayout_8.addWidget(self.text_file)
        self.btn_OpenFile = QtWidgets.QPushButton(self.frame_6)
        self.btn_OpenFile.setToolTip("")
        self.btn_OpenFile.setStatusTip("")
        self.btn_OpenFile.setWhatsThis("")
        self.btn_OpenFile.setAccessibleName("")
        self.btn_OpenFile.setAccessibleDescription("")
        self.btn_OpenFile.setObjectName("btn_OpenFile")
        self.horizontalLayout_8.addWidget(self.btn_OpenFile)
        self.verticalLayout_10.addWidget(self.frame_6)
        self.frame_8 = QtWidgets.QFrame(self.Classify)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_13 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_13.setFont(font)
        self.label_13.setToolTip("")
        self.label_13.setStatusTip("")
        self.label_13.setWhatsThis("")
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setAutoFillBackground(False)
        self.label_13.setTextFormat(QtCore.Qt.AutoText)
        self.label_13.setScaledContents(False)
        self.label_13.setWordWrap(True)
        self.label_13.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_11.addWidget(self.label_13)
        self.btn_Classify = QtWidgets.QPushButton(self.frame_8)
        self.btn_Classify.setToolTip("Will apply the saved model in tab 2")
        self.btn_Classify.setStatusTip("")
        self.btn_Classify.setWhatsThis("")
        self.btn_Classify.setAccessibleName("")
        self.btn_Classify.setAccessibleDescription("")
        self.btn_Classify.setObjectName("btn_Classify")
        self.verticalLayout_11.addWidget(self.btn_Classify)
        self.verticalLayout_10.addWidget(self.frame_8)
        self.frame_7 = QtWidgets.QFrame(self.Classify)
        self.frame_7.setAutoFillBackground(True)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_12 = QtWidgets.QLabel(self.frame_7)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_9.addWidget(self.label_12)
        self.results = QtWidgets.QPlainTextEdit(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.results.setFont(font)
        self.results.setToolTip("")
        self.results.setStatusTip("")
        self.results.setWhatsThis("")
        self.results.setAccessibleName("")
        self.results.setAccessibleDescription("")
        self.results.setPlainText("")
        self.results.setObjectName("results")
        self.verticalLayout_9.addWidget(self.results)
        self.verticalLayout_10.addWidget(self.frame_7)
        self.tabWidget.addTab(self.Classify, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Music Classification"))
        self.Dimensionality.setTitle(_translate("MainWindow", "Dimensionality Reduction"))
        self.label_2.setText(_translate("MainWindow", "Select normalizer:"))
        self.scaler_Dim.setItemText(0, _translate("MainWindow", "quantileNormal"))
        self.scaler_Dim.setItemText(1, _translate("MainWindow", "quantileUniform"))
        self.scaler_Dim.setItemText(2, _translate("MainWindow", "standard"))
        self.scaler_Dim.setItemText(3, _translate("MainWindow", "minMax"))
        self.scaler_Dim.setItemText(4, _translate("MainWindow", "maxAbs"))
        self.scaler_Dim.setItemText(5, _translate("MainWindow", "robust"))
        self.scaler_Dim.setItemText(6, _translate("MainWindow", "L2Norm"))
        self.label.setText(_translate("MainWindow", "Define variance, for PCA only:"))
        self.btn_LDA.setText(_translate("MainWindow", "LDA Components"))
        self.btn_PCA.setText(_translate("MainWindow", "PCA Components"))
        self.btn_PCA_Plot.setText(_translate("MainWindow", "PCA Analysis (Plot)"))
        self.btn_PlotLDA.setText(_translate("MainWindow", "Plot LDA (2 vectors)"))
        self.testModels.setTitle(_translate("MainWindow", "Test Classification Models"))
        self.select_LDA.setText(_translate("MainWindow", "LDA"))
        self.select_PCA.setText(_translate("MainWindow", "PCA"))
        self.label_5.setText(_translate("MainWindow", "Define variance, for PCA only:"))
        self.label_3.setText(_translate("MainWindow", "Dimensionality Reduction:"))
        self.label_4.setText(_translate("MainWindow", "Select normalizer:"))
        self.scaler_Test.setItemText(0, _translate("MainWindow", "quantileNormal"))
        self.scaler_Test.setItemText(1, _translate("MainWindow", "quantileUniform"))
        self.scaler_Test.setItemText(2, _translate("MainWindow", "standard"))
        self.scaler_Test.setItemText(3, _translate("MainWindow", "minMax"))
        self.scaler_Test.setItemText(4, _translate("MainWindow", "maxAbs"))
        self.scaler_Test.setItemText(5, _translate("MainWindow", "robust"))
        self.scaler_Test.setItemText(6, _translate("MainWindow", "L2Norm"))
        self.btn_CompareModels.setText(_translate("MainWindow", "Compare Models"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tests), _translate("MainWindow", "Pre-Processing_Tests"))
        self.parameters.setTitle(_translate("MainWindow", "Define Parameters"))
        self.label_6.setText(_translate("MainWindow", "Model:"))
        self.box_Model.setItemText(0, _translate("MainWindow", "LR"))
        self.box_Model.setItemText(1, _translate("MainWindow", "SGD"))
        self.box_Model.setItemText(2, _translate("MainWindow", "SVM"))
        self.box_Model.setItemText(3, _translate("MainWindow", "RF"))
        self.box_Model.setItemText(4, _translate("MainWindow", "extraTrees"))
        self.box_Model.setItemText(5, _translate("MainWindow", "kNN"))
        self.box_Model.setItemText(6, _translate("MainWindow", "MLP"))
        self.label_8.setText(_translate("MainWindow", "Normalizer:"))
        self.box_Scaler.setItemText(0, _translate("MainWindow", "quantileNormal"))
        self.box_Scaler.setItemText(1, _translate("MainWindow", "quantileUniform"))
        self.box_Scaler.setItemText(2, _translate("MainWindow", "standard"))
        self.box_Scaler.setItemText(3, _translate("MainWindow", "minMax"))
        self.box_Scaler.setItemText(4, _translate("MainWindow", "maxAbs"))
        self.box_Scaler.setItemText(5, _translate("MainWindow", "robust"))
        self.box_Scaler.setItemText(6, _translate("MainWindow", "L2Norm"))
        self.features.setTitle(_translate("MainWindow", "Feature Selection (optional)"))
        self.label_10.setText(_translate("MainWindow", "Select Feature:"))
        self.box_Feature.setItemText(0, _translate("MainWindow", "default (all)"))
        self.box_Feature.setItemText(1, _translate("MainWindow", "mfcc"))
        self.box_Feature.setItemText(2, _translate("MainWindow", "spec_contrast"))
        self.box_Feature.setItemText(3, _translate("MainWindow", "spec_bandwidth"))
        self.box_Feature.setItemText(4, _translate("MainWindow", "spec_rolloff"))
        self.box_Feature.setItemText(5, _translate("MainWindow", "spec_centroid"))
        self.box_Feature.setItemText(6, _translate("MainWindow", "chroma_cens"))
        self.box_Feature.setItemText(7, _translate("MainWindow", "chroma_cqt"))
        self.box_Feature.setItemText(8, _translate("MainWindow", "chroma_stft"))
        self.box_Feature.setItemText(9, _translate("MainWindow", "tonnetz"))
        self.box_Feature.setItemText(10, _translate("MainWindow", "rmse"))
        self.box_Feature.setItemText(11, _translate("MainWindow", "zcr"))
        self.label_7.setText(_translate("MainWindow", "Combine Features?"))
        self.btn_combineFeatures.setText(_translate("MainWindow", "Yes"))
        self.label_11.setText(_translate("MainWindow", "Select Features to Combine (use ctrl):"))
        __sortingEnabled = self.listFeatures.isSortingEnabled()
        self.listFeatures.setSortingEnabled(False)
        item = self.listFeatures.item(0)
        item.setText(_translate("MainWindow", "chroma_stft"))
        item = self.listFeatures.item(1)
        item.setText(_translate("MainWindow", "chroma_cens"))
        item = self.listFeatures.item(2)
        item.setText(_translate("MainWindow", "chroma_cqt"))
        item = self.listFeatures.item(3)
        item.setText(_translate("MainWindow", "spec_rolloff"))
        item = self.listFeatures.item(4)
        item.setText(_translate("MainWindow", "spec_bandwidth"))
        item = self.listFeatures.item(5)
        item.setText(_translate("MainWindow", "spec_centroid"))
        item = self.listFeatures.item(6)
        item.setText(_translate("MainWindow", "spec_contrast"))
        item = self.listFeatures.item(7)
        item.setText(_translate("MainWindow", "tonnetz"))
        item = self.listFeatures.item(8)
        item.setText(_translate("MainWindow", "zcr"))
        item = self.listFeatures.item(9)
        item.setText(_translate("MainWindow", "rmse"))
        item = self.listFeatures.item(10)
        item.setText(_translate("MainWindow", "mfcc"))
        self.listFeatures.setSortingEnabled(__sortingEnabled)
        self.btn_Results.setText(_translate("MainWindow", "Show Results"))
        self.btn_SaveModel.setToolTip(_translate("MainWindow", "Only saves models using all features"))
        self.btn_SaveModel.setText(_translate("MainWindow", "Save Model to Classify"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Results), _translate("MainWindow", "Model_Results"))
        self.label_9.setText(_translate("MainWindow", "Music File Location:"))
        self.btn_OpenFile.setText(_translate("MainWindow", "Open File"))
        self.label_13.setText(_translate("MainWindow", "Please, make sure you have saved a model by pressing the button \"Save Model to Classify\" in the previous tab. You can experiment with different models and test the same music file to check if the results vary."))
        self.btn_Classify.setText(_translate("MainWindow", "CLASSIFY"))
        self.label_12.setText(_translate("MainWindow", "RESULTS:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Classify), _translate("MainWindow", "Classify"))

